### ISSUE TITLE
add pagination for tags pages.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/news-theme#55] opened 2019-08-05 09:13 UTC
currently only a certain number of articles are displayed in each tag page.
more articles should be displayed if they have the specified tag.
similar functionality is available on search page and the main page.

**Comment by sunnyssr** [comment] 2019-08-07 19:52
I am able to achieve it by adding a button which is handled by infinitescroll. But the problem is that I don't know how to hide that button when there are no more articles.

**Comment by scissorsneedfoodtoo** [comment] 2019-08-20 06:27
Closed via #58

**Closed by scissorsneedfoodtoo** 2019-08-20 06:27 UTC
Labels: high-priority
